import "./Xtd.css";
import { cleanPage } from "../../utils/cleanPage";
export const Xtd = () => {
const main = document.querySelector("main");
cleanPage(main);
main.innerHTML = `
<div>
            <h2>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam sem fringilla ut morbi tincidunt augue. Purus ut faucibus pulvinar elementum integer enim neque volutpat. Id semper risus in hendrerit gravida rutrum quisque non tellus. Quisque non tellus orci ac. Mi eget mauris pharetra et ultrices neque ornare aenean euismod. Nunc consequat interdum varius sit amet mattis. Sed egestas egestas fringilla phasellus faucibus scelerisque. Varius duis at consectetur lorem. Vitae congue mauris rhoncus aenean. Diam sit amet nisl suscipit adipiscing. Rutrum quisque non tellus orci ac. Sit amet justo donec enim diam. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Ornare massa eget egestas purus viverra accumsan in nisl. Arcu risus quis varius quam quisque id. Feugiat scelerisque varius morbi enim nunc faucibus. Fermentum dui faucibus in ornare quam viverra.

Congue nisi vitae suscipit tellus mauris. Rhoncus dolor purus non enim praesent elementum. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero nunc. Mauris pharetra et ultrices neque ornare aenean. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Fringilla ut morbi tincidunt augue interdum velit. Tortor dignissim convallis aenean et tortor at. Nisl vel pretium lectus quam id leo in vitae. Eu sem integer vitae justo eget magna fermentum iaculis. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Ultricies mi quis hendrerit dolor magna eget. Odio facilisis mauris sit amet massa vitae. Bibendum neque egestas congue quisque. Eu sem integer vitae justo. Viverra vitae congue eu consequat ac felis. Elit pellentesque habitant morbi tristique senectus et netus et malesuada. Porttitor eget dolor morbi non.

Lorem donec massa sapien faucibus et. Neque viverra justo nec ultrices dui sapien eget. Iaculis urna id volutpat lacus laoreet non. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim. Fames ac turpis egestas sed tempus urna et. Tortor posuere ac ut consequat semper viverra nam. Blandit turpis cursus in hac habitasse platea dictumst. Malesuada nunc vel risus commodo viverra maecenas accumsan. Sagittis vitae et leo duis ut diam quam. Fermentum leo vel orci porta non pulvinar neque laoreet suspendisse. Elementum integer enim neque volutpat ac. Sed ullamcorper morbi tincidunt ornare massa eget. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Sodales ut eu sem integer vitae. In hac habitasse platea dictumst vestibulum rhoncus est.

Aliquet bibendum enim facilisis gravida neque convallis. Nibh praesent tristique magna sit amet purus gravida quis. Quis lectus nulla at volutpat diam ut. Amet aliquam id diam maecenas. Justo laoreet sit amet cursus sit amet dictum sit amet. Eleifend quam adipiscing vitae proin sagittis nisl. Sem et tortor consequat id. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit. Malesuada fames ac turpis egestas integer eget. Laoreet non curabitur gravida arcu ac tortor dignissim convallis. Hendrerit gravida rutrum quisque non. Massa ultricies mi quis hendrerit dolor magna eget. Sed euismod nisi porta lorem mollis aliquam. Eget gravida cum sociis natoque.

Ultrices dui sapien eget mi proin sed libero. Feugiat vivamus at augue eget arcu dictum. Lobortis feugiat vivamus at augue eget arcu dictum. Odio ut enim blandit volutpat maecenas. Non curabitur gravida arcu ac tortor. Id volutpat lacus laoreet non curabitur gravida arcu. Nisi est sit amet facilisis. Scelerisque fermentum dui faucibus in ornare quam viverra orci sagittis. Suspendisse ultrices gravida dictum fusce. Ut porttitor leo a diam sollicitudin tempor. Cursus risus at ultrices mi. Diam sollicitudin tempor id eu nisl nunc. Phasellus vestibulum lorem sed risus ultricies.

Pellentesque adipiscing commodo elit at imperdiet dui accumsan sit amet. Sed augue lacus viverra vitae congue eu consequat. Cursus risus at ultrices mi tempus imperdiet nulla. Tempus egestas sed sed risus pretium quam. A cras semper auctor neque vitae. Augue mauris augue neque gravida in fermentum. Semper risus in hendrerit gravida rutrum. Dolor sit amet consectetur adipiscing elit duis tristique sollicitudin. Fusce id velit ut tortor pretium viverra suspendisse potenti. Ultricies lacus sed turpis tincidunt id aliquet risus feugiat in. Suspendisse potenti nullam ac tortor vitae. Ipsum suspendisse ultrices gravida dictum fusce. Vitae tortor condimentum lacinia quis vel eros donec ac odio. Volutpat ac tincidunt vitae semper quis lectus nulla at. Donec et odio pellentesque diam volutpat. Elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Aliquet nec ullamcorper sit amet. Et leo duis ut diam. Pretium aenean pharetra magna ac placerat vestibulum lectus mauris.

Nisl purus in mollis nunc sed id semper. Semper feugiat nibh sed pulvinar proin gravida hendrerit. Mauris augue neque gravida in fermentum et sollicitudin ac. Risus commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Amet facilisis magna etiam tempor orci eu lobortis elementum. Consectetur libero id faucibus nisl. Auctor augue mauris augue neque. Aliquet bibendum enim facilisis gravida neque convallis a cras. Nunc eget lorem dolor sed viverra ipsum nunc. At imperdiet dui accumsan sit amet nulla. Nibh mauris cursus mattis molestie a iaculis at erat pellentesque. Nascetur ridiculus mus mauris vitae ultricies leo. Vel eros donec ac odio tempor orci dapibus.

In est ante in nibh mauris cursus mattis. Tortor at auctor urna nunc id. Tempus egestas sed sed risus. Amet mattis vulputate enim nulla aliquet porttitor lacus. Cursus in hac habitasse platea dictumst quisque sagittis purus sit. At ultrices mi tempus imperdiet nulla malesuada. Dignissim cras tincidunt lobortis feugiat vivamus at. Proin libero nunc consequat interdum varius sit amet mattis vulputate. Vel quam elementum pulvinar etiam non quam lacus suspendisse faucibus. Senectus et netus et malesuada fames. Eu lobortis elementum nibh tellus molestie nunc non. Eu facilisis sed odio morbi quis commodo odio aenean. Bibendum neque egestas congue quisque egestas diam. Id aliquet risus feugiat in ante metus dictum at. Arcu non odio euismod lacinia at quis risus. Id neque aliquam vestibulum morbi blandit cursus risus. Varius quam quisque id diam. Mauris vitae ultricies leo integer malesuada nunc.
            </h2>
        </div>
        `;
};
